### ISSUE TITLE
Hello from Hydra

### ISSUE THREAD

**Issue by omry** [codegram/calbert#1]
Hi,
I am the author of Hydra, happy to see you are using it for your project!
Feel free to join the Hydra [chat](https://hydra-framework.zulipchat.com/#) if you have any questions.

Glancing at your config, I don't have much feedback (you are just getting started) except to say that it looks like you are on the right track, using composition.

A comment about your readme:

> In most commands, you need to provide absolute paths with $PWD since these are Hydra runs and they don't run on the current directory.

There are a few APIs documented [here](https://hydra.cc/docs/tutorial/working_directory#original-working-directory) that can help you eliminate this restriction.

Happy configuring! :)

**Comment by omry** [comment]
Oh, and the Hydra website is now https://hydra.cc, please update your readme. (The redirect in place will go away when the domain expires).

**Comment by txus** [comment]
Thank you so much! 
All fixed in https://github.com/codegram/calbert/commit/16913b488c3f1357db01ff5d46b042fc0aaaae78 :) Keep up the great work!

**Comment by omry** [comment]
Happy to help :)

**Comment by omry** [comment]
I suggest you follow the Hydra releases, the are some exciting things coming.
