### ISSUE TITLE
simplify test by using hydra.experimental.compose()

### ISSUE THREAD

**Issue by omry** [codegram/calbert#2]
https://github.com/codegram/calbert/blob/7e0dc7a023ad12a74df15f8c41ec518dd8142513/tests/training_test.py#L20-L84

[Hydra compose API](https://hydra.cc/docs/advanced/compose_api) lets you compose a config on the spot just like the config composed by hydra.main().
You can override things in it by passing key=value list of string overrides.

You should be able to simplify your test at lot with it, reusing the same config and just overriding the paths inside to those created by the test.

**Comment by txus** [comment]
Thank you! It really could help :) I'll have a look!

**Comment by omry** [comment]
Awesome.
two things:
1. This is an experimental API. let me know you have any feedback.
2. Feel free to join the Hydra [chat](https://hydra-framework.zulipchat.com) if you have questions about Hydra.

**Comment by txus** [comment]
Gonna have a look in the next release, closing for now.
